### ISSUE TITLE
[FEAT]: Implement MFA

### ISSUE THREAD

**Issue by StevanFreeborn** [StevanFreeborn/onspring-qa-playwright-reports#35]
## Initial Thoughts

- [ ] When user logs in and they haven't setup MFA yet we should prompt them to setup MFA
- [ ] User should be able to setup MFA using QR code
- [ ] When user logs in and they have setup MFA they should be required to enter a one-time password
- [ ] When a user logs in and they do not have access to their authenticator code they should have the option to enter a recovery code to login
- [ ] A user should be able to re-setup MFA

### Views

- [ ] TOTP Challenge View
- [ ] Recovery Code Challenge View
- [ ] Profile View
- [ ] Verify MFA Setup
- [ ] Recovery Codes

### Data

- [ ] User will need to indicate whether MFA is enabled or not
- [ ] User will need shared secret key [❗] This needs to be stored encrypted. This is a new piece of functionality
- [ ] User will need to have reference to recovery codes
- [ ] User Session will need some way to indicate authenticated, but also successfully passed OTP.

### Enabling MFA

**TODO:** Add flow description

### Disabling MFA

**TODO:** Add flow description

### Using OTP

**TODO:** Add flow description

### Using Recovery Code

**TODO:** Add flow description
